const cfg=window.DOCTOR_GPS_CONFIG||{};const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);let paymentRows=[];
const $=id=>document.getElementById(id);const money=v=>`${Number(v||0).toLocaleString('ru-RU')} ₽`;const date=v=>v?new Date(v).toLocaleString('ru-RU'):'—';
async function boot(){const {data:{session}}=await sb.auth.getSession();session?openApp(session):showLogin()}
function showLogin(){$('login').hidden=false;$('app').hidden=true}
async function openApp(session){const {data:admin}=await sb.from('doctor_gps_admins').select('user_id').eq('user_id',session.user.id).maybeSingle();if(!admin){await sb.auth.signOut();$('loginError').textContent='Нет прав администратора';return showLogin()}$('login').hidden=true;$('app').hidden=false;$('adminEmail').textContent=session.user.email;await Promise.all([loadDashboard(),loadSettings(),loadPayments(),loadUsers()])}
$('loginButton').onclick=async()=>{ $('loginError').textContent='';const {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});error?$('loginError').textContent=error.message:openApp(data.session)};
$('logout').onclick=async()=>{await sb.auth.signOut();showLogin()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(x=>x.hidden=x.id!==b.dataset.page);$('pageTitle').textContent=b.textContent});
async function loadDashboard(){const {data}=await sb.from('doctor_gps_dashboard').select('*').single();if(data){$('usersTotal').textContent=data.users_total;$('activeSubscriptions').textContent=data.active_subscriptions;$('activeTrials').textContent=data.active_trials;$('revenueMonth').textContent=money(data.revenue_month)}}
function rows(items,type){if(!items?.length)return '<p>Данных пока нет</p>';return items.map(x=>type==='payment'?`<div class="row"><span>${x.user_id.slice(0,8)}…</span><span>${x.provider}</span><span>${money(x.amount)}</span><span class="badge">${x.status}</span></div>`:`<div class="row"><span>${x.user_id.slice(0,8)}…</span><span>${x.status}</span><span>${x.provider||'—'}</span><span>${date(x.expires_at)}</span></div>`).join('')}
async function loadPayments(){const {data}=await sb.from('doctor_gps_payments').select('*').order('created_at',{ascending:false}).limit(500);paymentRows=data||[];$('paymentsTable').innerHTML=rows(paymentRows,'payment');$('recentPayments').innerHTML=rows(paymentRows.slice(0,8),'payment')}
async function loadUsers(){const {data}=await sb.from('doctor_gps_subscriptions').select('*').order('updated_at',{ascending:false});$('usersTable').innerHTML=rows(data,'user')}
async function loadSettings(){const {data}=await sb.from('doctor_gps_settings').select('*').single();if(!data)return;$('provider').value=data.active_provider;$('price').value=data.monthly_price;$('trialDays').value=data.trial_days;$('paymentsEnabled').checked=data.payments_enabled}
$('saveSettings').onclick=async()=>{const {data:{user}}=await sb.auth.getUser();const {error}=await sb.from('doctor_gps_settings').update({active_provider:$('provider').value,monthly_price:Number($('price').value),trial_days:Number($('trialDays').value),payments_enabled:$('paymentsEnabled').checked,updated_at:new Date().toISOString(),updated_by:user.id}).eq('id',true);$('settingsMessage').textContent=error?error.message:'Настройки сохранены'};
$('exportCsv').onclick=()=>{const head='Дата,Пользователь,Провайдер,Сумма,Статус\n';const body=paymentRows.map(x=>[date(x.created_at),x.user_id,x.provider,x.amount,x.status].join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([head+body],{type:'text/csv;charset=utf-8'}));a.download='doctor-gps-payments.csv';a.click()};boot();
